export const guidesData = [
  {
    id: 1,
    title: "Что делать с батарейками",
    category: "home",
    image: 'batteries',
    link: "/pages/guides/guides_pages/batteries.html",
  },
  {
    id: 2,
    title: "Получение водительских прав",
    category: "docs",
    image: 'driver-license',
    link: "/pages/guides/guides_pages/driver-license.html",
  },
  {
    id: 3,
    title: "Как завести питомца, если ты живешь один (реалии vs мечты)",
    category: "home",
    image: 'zavesti-pitomca',
    link: "/pages/guides/guides_pages/zavesti-pitomca.html",
  },
  {
    id: 4,
    title: "Как договориться о зарплате",
    category: "career",
    image: 'kak-dogovoritsya-o-zarplate',
    link: "/pages/guides/guides_pages/kak-dogovoritsya-o-zarplate.html",
  },

  {
    id: 5,
    title: "Как пользоваться кредиткой без процентов",
    category: "finance",
    image: 'kreditka-bez-procentov',
    link: "/pages/guides/guides_pages/kreditka-bez-procentov.html",
  },
  {
    id: 6,
    title: "Как экономить на бытовой химии (и не отравиться)",
    category: "home",
    image: 'bytovaya-himiya',
    link: "/pages/guides/guides_pages/bytovaya-himiya.html",
  },
  {
    id: 7,
    title: "Как не сдохнуть от аллергии в сезон (и когда бежать к врачу)",
    category: "health",
    image: 'kak-ne-sdohnut-ot-allergii-v-sezon',
    link: "/pages/guides/guides_pages/kak-ne-sdohnut-ot-allergii-v-sezon.html",
  },
  {
    id: 8,
    title: "Как пользоваться Notion/Trello/любым планером без фанатизма",
    category: "life",
    image: 'kak-polzovatsya-lyubym-planerom-bez-fanatizma',
    link: "/pages/guides/guides_pages/kak-polzovatsya-lyubym-planerom-bez-fanatizma.html",
  },
  {
    id: 9,
    title: "Как пережить больничный без потери денег и нервов",
    category: "health",
    image: 'kak-perezhit-bolnichnyj-bez-poteri-deneg-i-nervov',
    link: "/pages/guides/guides_pages/kak-perezhit-bolnichnyj-bez-poteri-deneg-i-nervov.html",
  },
  {
    id: 10,
    title: "Как оформить ИНН, если ты фрилансер",
    category: "docs",
    image: 'oformlenie-inn',
    link: "/pages/guides/guides_pages/oformlenie-inn.html",
  },
  {
    id: 11,
    title: "Тайм-менеджмент для тех, кто ненавидит планировать",
    category: "life",
    image: 'tajm-menedzhment-dlya-tekh-kto-nenavidit-planirovat',
    link: "/pages/guides/guides_pages/tajm-menedzhment-dlya-tekh-kto-nenavidit-planirovat.html",

  },
  {
    id: 12,
    title: "Как превратить фриланс в постоянный доход (и не сойти с ума)",
    category: "career",
    image: 'kak-prevratit-frilans-v-postoyannyj-dohod',
    link: "/pages/guides/guides_pages/kak-prevratit-frilans-v-postoyannyj-dohod.html",
  },
  {
    id: 13,
    title: "Как начать откладывать, если в конце месяца всегда ноль",
    category: "finance",
    image: 'kak-nachat-otkladyvat',
    link: "/pages/guides/guides_pages/kak-nachat-otkladyvat.html",
  },
  {
    id: 14,
    title: "Как пройти ассессмент и не вылететь на первом же тесте",
    category: "career",
    image: 'kak-projti-assessment-i-ne-vyletet-na-pervom-zhe-teste',
    link: "/pages/guides/guides_pages/kak-projti-assessment-i-ne-vyletet-na-pervom-zhe-teste.html",
  },
  {
    id: 15,
    title: "Как пройти диспансеризацию: от записи до результатов",
    category: "health",
    image: 'kak-projti-dispanserizaciyu-ot-zapisi-do-rezultatov',
    link: "/pages/guides/guides_pages/kak-projti-dispanserizaciyu-ot-zapisi-do-rezultatov.html",
  },
  {
    id: 16,
    title: "Как восстановить СНИЛС, если потерял",
    category: "docs",
    image: 'vosstanovlenie-snils',
    link: "/pages/guides/guides_pages/vosstanovlenie-snils.html",
  },
  {
    id: 17,
    title: "Как не попасть на мошенников в интернете",
    category: "finance",
    image: 'moshenniki-v-internete',
    link: "/pages/guides/guides_pages/moshenniki-v-internete.html",

  },
  {
    id: 18,
    title: "Как сдать квартиру, если ты собственник",
    category: "home",
    image: 'sdacha-kvartiry-v-arendu',
    link: "/pages/guides/guides_pages/sdacha-kvartiry-v-arendu.html",
  },
  {
    id: 19,
    title: "Как разобраться в рецептах и не купить лишнего в аптеке",
    category: "health",
    image: 'kak-razobratsya-v-receptah-i-ne-kupit-lishnego-v-apteke',
    link: "/pages/guides/guides_pages/kak-razobratsya-v-receptah-i-ne-kupit-lishnego-v-apteke.html",
  },
  {
    id: 20,
    title: "Как вести переговоры с клиентом или партнером",
    category: "career",
    image: 'kak-vesti-peregovory-s-klientom-ili-partnerom',
    link: "/pages/guides/guides_pages/kak-vesti-peregovory-s-klientom-ili-partnerom.html",
  },
  {
    id: 21,
    title: "Как вести себя в первый месяц на новой работе",
    category: "career",
    image: 'kak-vesti-sebya-v-pervyj-mesyac-na-novoj-rabote',
    link: "/pages/guides/guides_pages/kak-vesti-sebya-v-pervyj-mesyac-na-novoj-rabote.html",
  },
  {
    id: 22,
    title: "Как выстраивать режим, когда работаешь из дома",
    category: "life",
    image: 'rezhim-kogda-rabotaesh-iz-doma',
    link: "/pages/guides/guides_pages/rezhim-kogda-rabotaesh-iz-doma.html",
  },
  {
    id: 23,
    title: "Как получить справку 2-НДФЛ (и зачем она вообще нужна)",
    category: "docs",
    image: 'poluchenie-spravki-2-ndfl',
    link: "/pages/guides/guides_pages/poluchenie-spravki-2-ndfl.html",
  },
  {
    id: 24,
    title: "Первая помощь при распространенных ситуациях",
    category: "health",
    image: 'pervaya-pomoshch-pri-rasprostranennyh-situaciyah',
    link: "/pages/guides/guides_pages/pervaya-pomoshch-pri-rasprostranennyh-situaciyah.html",
  },
  {
    id: 25,
    title: "Как завести друзей во взрослом возрасте",
    category: "life",
    image: 'druzya-vo-vzroslom-vozraste',
    link: "/pages/guides/guides_pages/druzya-vo-vzroslom-vozraste.html",
  },
  {
    id: 26,
    title: "Как вести бюджет, если ненавидишь таблицы",
    category: "finance",
    image: 'kak-vesti-byudzhet',
    link: "/pages/guides/guides_pages/kak-vesti-byudzhet.html",
  },
  {
    id: 27,
    title: "Как просить обратную связь, если боишься критики",
    category: "career",
    image: 'kak-prosit-obratnuyu-svyaz',
    link: "/pages/guides/guides_pages/kak-prosit-obratnuyu-svyaz.html",
  },
  {
    id: 28,
    title: "Как найти хобби, если кажется, что ничего не нравится",
    category: "life",
    image: 'kak-najti-hobbi',
    link: "/pages/guides/guides_pages/kak-najti-hobbi.html",
  },
  {
    id: 29,
    title: "Как выбрать врача и не ошибиться",
    category: "health",
    image: 'kak-vybrat-vracha-i-ne-oshibitsya',
    link: "/pages/guides/guides_pages/kak-vybrat-vracha-i-ne-oshibitsya.html",

  },
  {
    id: 30,
    title: "Как искать работу, когда у тебя вообще нет опыта",
    category: "career",
    image: 'kak-iskat-rabotu-kogda-u-tebya-net-opyta',
    link: "/pages/guides/guides_pages/kak-iskat-rabotu-kogda-u-tebya-net-opyta.html",
  },
  {
    id: 31,
    title: "Как пережить расставание и не разрушить свою жизнь",
    category: "life",
    image: 'kak-perezhit-rasstavanie',
    link: "/pages/guides/guides_pages/kak-perezhit-rasstavanie.html",
  },
  {
    id: 32,
    title: "Увольнение по собственному желанию: как уйти красиво, чтобы не жалеть",
    category: "career",
    image: 'uvolnenie-po-sobstvennomu-zhelaniyu',
    link: "/pages/guides/guides_pages/uvolnenie-po-sobstvennomu-zhelaniyu.html",

  },
  {
    id: 33,
    title: "Как перестать зависать в телефоне перед сном",
    category: "life",
    image: 'perestat-zavisat-v-telefone-pered-snom',
    link: "/pages/guides/guides_pages/perestat-zavisat-v-telefone-pered-snom.html",
  },
  {
    id: 34,
    title: "Как собрать документы на вычет",
    category: "docs",
    image: 'dokumenty-na-nalogovyj-vychet',
    link: "/pages/guides/guides_pages/dokumenty-na-nalogovyj-vychet.html",
  },
  {
    id: 35,
    title: "Как перестать стесняться себя и начать жить спокойно",
    category: "life",
    image: 'perestat-stesnyatsya-sebya',
    link: "/pages/guides/guides_pages/perestat-stesnyatsya-sebya.html",
  },
  {
    id: 36,
    title: "Как понять, что у тебя депрессия (и куда идти)",
    category: "health",
    image: 'kak-ponyat-chto-u-tebya-depressiya',
    link: "/pages/guides/guides_pages/kak-ponyat-chto-u-tebya-depressiya.html",
  },
  {
    id: 38,
    title: "Как пройти стажировку и получить оффер",
    category: "career",
    image: 'kak-projti-stazhirovku-i-poluchit-offer',
    link: "/pages/guides/guides_pages/kak-projti-stazhirovku-i-poluchit-offer.html",
  },
  {
    id: 39,
    title: "Как читать выписку по карте и находить лишние списания",
    category: "finance",
    image: 'chitaem-vypisku-po-karte',
    link: "/pages/guides/guides_pages/chitaem-vypisku-po-karte.html",
  },
  {
    id: 40,
    title: "Как пробиться в креатив, если у тебя нет ни портфолио, ни связей",
    category: "career",
    image: 'kak-probitsya-v-kreativ',
    link: "/pages/guides/guides_pages/kak-probitsya-v-kreativ.html",
  },
  {
    id: 41,
    title: "Как выбрать банк для первой дебетовой карты",
    category: "finance",
    image: 'pervaya-debetovaya-karta',
    link: "/pages/guides/guides_pages/pervaya-debetovaya-karta.html",
  },
  {
    id: 42,
    title: "Как безопасно оплачивать коммуналку онлайн (чтобы не кинули)",
    category: "home",
    image: 'oplachivaem-kommunalku-onlajn',
    link: "/pages/guides/guides_pages/oplachivaem-kommunalku-onlajn.html",
  },
  {
    id: 43,
    title: "Как написать резюме, чтобы тебя заметили среди 500 других",
    category: "career",
    image: 'kak-napisat-rezyume-chtoby-tebya-zametili',
    link: "/pages/guides/guides_pages/kak-napisat-rezyume-chtoby-tebya-zametili.html",
  },
  {
    id: 44,
    title: "Как пережить зиму в квартире: советы по теплу и счетам",
    category: "home",
    image: 'zima-v-kvartire',
    link: "/pages/guides/guides_pages/zima-v-kvartire.html",
  },
  {
    id: 45,
    title: "Что спросить на собеседовании, чтобы не попасть в болото",
    category: "career",
    image: 'chto-sprosit-na-sobesedovanii',
    link: "/pages/guides/guides_pages/chto-sprosit-na-sobesedovanii.html",
  },
  {
    id: 46,
    title: "Как внедрить полезную привычку и не бросить через неделю",
    category: "life",
    image: 'kak-vnedrit-poleznuyu-privychku',
    link: "/pages/guides/guides_pages/kak-vnedrit-poleznuyu-privychku.html",
  },
  {
    id: 47,
    title: "Как подготовиться к приему врача, чтобы не забыть спросить важное",
    category: "health",
    image: 'kak-podgotovitsya-k-priemu-vracha-chtoby-ne-zabyt-sprosit-vazhnoe',
    link: "/pages/guides/guides_pages/kak-podgotovitsya-k-priemu-vracha-chtoby-ne-zabyt-sprosit-vazhnoe.html",
  },
  {
    id: 48,
    title: "Как поменять паспорт в 20 и 45",
    category: "docs",
    image: 'zamena-pasporta',
    link: "/pages/guides/guides_pages/zamena-pasporta.html",
  },
  {
    id: 49,
    title: "Как получить загранпаспорт в 2026",
    category: "docs",
    image: 'poluchenie-zagranpasporta',
    link: "/pages/guides/guides_pages/poluchenie-zagranpasporta.html",
  },
  {
    id: 50,
    title: "Как выжить в поликлинике: лайфхаки по записи, талонам и очередям",
    category: "health",
    image: 'kak-vyzhit-v-poliklinike',
    link: "/pages/guides/guides_pages/kak-vyzhit-v-poliklinike.html",

  },
  {
    id: 51,
    title: "Как оформить временную регистрацию при переезде",
    category: "docs",
    image: 'oformlenie-vremennoj-registracii',
    link: "/pages/guides/guides_pages/oformlenie-vremennoj-registracii.html",
  },
  {
    id: 52,
    title: "Как пройти собеседование, если трясутся коленки",
    category: "career",
    image: 'kak-projti-sobesedovanie-esli-tryasutsya-kolenki',
    link: "/pages/guides/guides_pages/kak-projti-sobesedovanie-esli-tryasutsya-kolenki.html",
  },
  {
    id: 53,
    title: "Рецепты выживания для тех, кто ненавидит готовить",
    category: "home",
    image: 'recepty-vyzhivaniya',
    link: "/pages/guides/guides_pages/recepty-vyzhivaniya.html",
  },
  {
    id: 54,
    title: "Как проверить договор на типичные ловушки (без юриста)",
    category: "docs",
    image: 'proverka-dogovora',
    link: "/pages/guides/guides_pages/proverka-dogovora.html",
  },
  {
    id: 37,
    title: "Как отвечать на вопрос «расскажите о себе»",
    category: "career",
    image: 'kak-otvechat-na-vopros-rasskazhite-o-sebe',
    link: "/pages/guides/guides_pages/kak-otvechat-na-vopros-rasskazhite-o-sebe.html",
  },
];
