export const guidesData = [
  {
    id: 1,
    title: "Что делать с\u00A0батарейками",
    category: "home",
    image: 'batteries',
    link: "/pages/guides/guides_pages/batteries.html",
  },
  {
    id: 2,
    title: "Получение водительских прав",
    category: "docs",
    image: 'driver-license',
    link: "/pages/guides/guides_pages/driver-license.html",
  },
  {
    id: 3,
    title: "Как завести питомца, если\u00A0ты\u00A0живешь один (реалии vs\u00A0мечты)",
    category: "home",
    image: 'zavesti-pitomca',
    link: "/pages/guides/guides_pages/zavesti-pitomca.html",
  },
  {
    id: 4,
    title: "Как договориться о\u00A0зарплате",
    category: "career",
    image: 'kak-dogovoritsya-o-zarplate',
    link: "/pages/guides/guides_pages/kak-dogovoritsya-o-zarplate.html",
  },

  {
    id: 5,
    title: "Как пользоваться кредиткой без\u00A0процентов",
    category: "finance",
    image: 'kreditka-bez-procentov',
    link: "/pages/guides/guides_pages/kreditka-bez-procentov.html",
  },
  {
    id: 6,
    title: "Как экономить на\u00A0бытовой химии (и\u00A0не\u00A0отравиться)",
    category: "home",
    image: 'bytovaya-himiya',
    link: "/pages/guides/guides_pages/bytovaya-himiya.html",
  },
  {
    id: 7,
    title: "Как не\u00A0сдохнуть от\u00A0аллергии в\u00A0сезон (и\u00A0когда бежать к\u00A0врачу)",
    category: "health",
    image: 'kak-ne-sdohnut-ot-allergii-v-sezon',
    link: "/pages/guides/guides_pages/kak-ne-sdohnut-ot-allergii-v-sezon.html",
  },
  {
    id: 8,
    title: "Как пользоваться Notion/Trello/любым планером без\u00A0фанатизма",
    category: "life",
    image: 'kak-polzovatsya-lyubym-planerom-bez-fanatizma',
    link: "/pages/guides/guides_pages/kak-polzovatsya-lyubym-planerom-bez-fanatizma.html",
  },
  {
    id: 46,
    title: "Как выбрать квартиру и\u00A0не\u00A0пожалеть через месяц",
    category: "home",
    image: 'kak-vybrat-kvartiru-i-ne-pozhalet-cherez-mesyac',
    link: "/pages/guides/guides_pages/kak-vybrat-kvartiru-i-ne-pozhalet-cherez-mesyac.html",
  },
  {
    id: 9,
    title: "Как пережить больничный без\u00A0потери денег и\u00A0нервов",
    category: "health",
    image: 'kak-perezhit-bolnichnyj-bez-poteri-deneg-i-nervov',
    link: "/pages/guides/guides_pages/kak-perezhit-bolnichnyj-bez-poteri-deneg-i-nervov.html",
  },
  {
    id: 10,
    title: "Как оформить ИНН, если\u00A0ты\u00A0фрилансер",
    category: "docs",
    image: 'oformlenie-inn',
    link: "/pages/guides/guides_pages/oformlenie-inn.html",
  },
  {
    id: 11,
    title: "Тайм-менеджмент для\u00A0тех, кто\u00A0ненавидит планировать",
    category: "life",
    image: 'tajm-menedzhment-dlya-tekh-kto-nenavidit-planirovat',
    link: "/pages/guides/guides_pages/tajm-menedzhment-dlya-tekh-kto-nenavidit-planirovat.html",

  },
  {
    id: 12,
    title: "Как превратить фриланс в\u00A0постоянный доход (и\u00A0не\u00A0сойти с ума)",
    category: "career",
    image: 'kak-prevratit-frilans-v-postoyannyj-dohod',
    link: "/pages/guides/guides_pages/kak-prevratit-frilans-v-postoyannyj-dohod.html",
  },
  {
    id: 13,
    title: "Как начать откладывать, если\u00A0в конце месяца всегда ноль",
    category: "finance",
    image: 'kak-nachat-otkladyvat',
    link: "/pages/guides/guides_pages/kak-nachat-otkladyvat.html",
  },
  {
    id: 14,
    title: "Как пройти ассессмент и\u00A0не\u00A0вылететь на\u00A0первом же тесте",
    category: "career",
    image: 'kak-projti-assessment-i-ne-vyletet-na-pervom-zhe-teste',
    link: "/pages/guides/guides_pages/kak-projti-assessment-i-ne-vyletet-na-pervom-zhe-teste.html",
  },
  {
    id: 15,
    title: "Как пройти диспансеризацию: от\u00A0записи до результатов",
    category: "health",
    image: 'kak-projti-dispanserizaciyu-ot-zapisi-do-rezultatov',
    link: "/pages/guides/guides_pages/kak-projti-dispanserizaciyu-ot-zapisi-do-rezultatov.html",
  },
  {
    id: 16,
    title: "Как восстановить СНИЛС, если\u00A0потерял",
    category: "docs",
    image: 'vosstanovlenie-snils',
    link: "/pages/guides/guides_pages/vosstanovlenie-snils.html",
  },
  {
    id: 17,
    title: "Как не\u00A0попасть на\u00A0мошенников в\u00A0интернете",
    category: "finance",
    image: 'moshenniki-v-internete',
    link: "/pages/guides/guides_pages/moshenniki-v-internete.html",

  },
  {
    id: 18,
    title: "Как сдать квартиру, если\u00A0ты\u00A0собственник",
    category: "home",
    image: 'sdacha-kvartiry-v-arendu',
    link: "/pages/guides/guides_pages/sdacha-kvartiry-v-arendu.html",
  },
  {
    id: 19,
    title: "Как разобраться в\u00A0рецептах и\u00A0не\u00A0купить лишнего в\u00A0аптеке",
    category: "health",
    image: 'kak-razobratsya-v-receptah-i-ne-kupit-lishnego-v-apteke',
    link: "/pages/guides/guides_pages/kak-razobratsya-v-receptah-i-ne-kupit-lishnego-v-apteke.html",
  },
  {
    id: 20,
    title: "Как вести переговоры с клиентом или\u00A0партнером",
    category: "career",
    image: 'kak-vesti-peregovory-s-klientom-ili-partnerom',
    link: "/pages/guides/guides_pages/kak-vesti-peregovory-s-klientom-ili-partnerom.html",
  },
  {
    id: 21,
    title: "Как вести себя в\u00A0первый месяц на\u00A0новой работе",
    category: "career",
    image: 'kak-vesti-sebya-v-pervyj-mesyac-na-novoj-rabote',
    link: "/pages/guides/guides_pages/kak-vesti-sebya-v-pervyj-mesyac-na-novoj-rabote.html",
  },
  {
    id: 22,
    title: "Как выстраивать режим, когда работаешь из\u00A0дома",
    category: "life",
    image: 'rezhim-kogda-rabotaesh-iz-doma',
    link: "/pages/guides/guides_pages/rezhim-kogda-rabotaesh-iz-doma.html",
  },
  {
    id: 23,
    title: "Как получить справку 2-НДФЛ (и\u00A0зачем она вообще нужна)",
    category: "docs",
    image: 'poluchenie-spravki-2-ndfl',
    link: "/pages/guides/guides_pages/poluchenie-spravki-2-ndfl.html",
  },
  {
    id: 24,
    title: "Первая помощь при\u00A0распространенных ситуациях",
    category: "health",
    image: 'pervaya-pomoshch-pri-rasprostranennyh-situaciyah',
    link: "/pages/guides/guides_pages/pervaya-pomoshch-pri-rasprostranennyh-situaciyah.html",
  },
  {
    id: 25,
    title: "Как завести друзей во\u00A0взрослом возрасте",
    category: "life",
    image: 'druzya-vo-vzroslom-vozraste',
    link: "/pages/guides/guides_pages/druzya-vo-vzroslom-vozraste.html",
  },
  {
    id: 26,
    title: "Как вести бюджет, если\u00A0ненавидишь таблицы",
    category: "finance",
    image: 'kak-vesti-byudzhet',
    link: "/pages/guides/guides_pages/kak-vesti-byudzhet.html",
  },
  {
    id: 27,
    title: "Как просить обратную связь, если\u00A0боишься критики",
    category: "career",
    image: 'kak-prosit-obratnuyu-svyaz',
    link: "/pages/guides/guides_pages/kak-prosit-obratnuyu-svyaz.html",
  },
  {
    id: 28,
    title: "Как найти хобби, если\u00A0кажется, что\u00A0ничего не\u00A0нравится",
    category: "life",
    image: 'kak-najti-hobbi',
    link: "/pages/guides/guides_pages/kak-najti-hobbi.html",
  },
  {
    id: 30,
    title: "Как искать работу, когда у\u00A0тебя вообще нет\u00A0опыта",
    category: "career",
    image: 'kak-iskat-rabotu-kogda-u-tebya-net-opyta',
    link: "/pages/guides/guides_pages/kak-iskat-rabotu-kogda-u-tebya-net-opyta.html",
  },
  {
    id: 31,
    title: "Как пережить расставание и\u00A0не\u00A0разрушить свою жизнь",
    category: "life",
    image: 'kak-perezhit-rasstavanie',
    link: "/pages/guides/guides_pages/kak-perezhit-rasstavanie.html",
  },
  {
    id: 32,
    title: "Увольнение по\u00A0собственному желанию: как уйти красиво, чтобы не\u00A0жалеть",
    category: "career",
    image: 'uvolnenie-po-sobstvennomu-zhelaniyu',
    link: "/pages/guides/guides_pages/uvolnenie-po-sobstvennomu-zhelaniyu.html",

  },
  {
    id: 33,
    title: "Как перестать зависать в\u00A0телефоне перед сном",
    category: "life",
    image: 'perestat-zavisat-v-telefone-pered-snom',
    link: "/pages/guides/guides_pages/perestat-zavisat-v-telefone-pered-snom.html",
  },
  {
    id: 34,
    title: "Как собрать документы на\u00A0вычет",
    category: "docs",
    image: 'dokumenty-na-nalogovyj-vychet',
    link: "/pages/guides/guides_pages/dokumenty-na-nalogovyj-vychet.html",
  },
  {
    id: 35,
    title: "Как перестать стесняться себя и\u00A0начать жить спокойно",
    category: "life",
    image: 'perestat-stesnyatsya-sebya',
    link: "/pages/guides/guides_pages/perestat-stesnyatsya-sebya.html",
  },
  {
    id: 36,
    title: "Как понять, что\u00A0у тебя депрессия (и\u00A0куда идти)",
    category: "health",
    image: 'kak-ponyat-chto-u-tebya-depressiya',
    link: "/pages/guides/guides_pages/kak-ponyat-chto-u-tebya-depressiya.html",
  },
  {
    id: 38,
    title: "Как пройти стажировку и\u00A0получить оффер",
    category: "career",
    image: 'kak-projti-stazhirovku-i-poluchit-offer',
    link: "/pages/guides/guides_pages/kak-projti-stazhirovku-i-poluchit-offer.html",
  },
  {
    id: 39,
    title: "Как читать выписку по\u00A0карте и\u00A0находить лишние списания",
    category: "finance",
    image: 'chitaem-vypisku-po-karte',
    link: "/pages/guides/guides_pages/chitaem-vypisku-po-karte.html",
  },
  {
    id: 40,
    title: "Как пробиться в\u00A0креатив, если\u00A0у тебя нет\u00A0ни портфолио, ни\u00A0связей",
    category: "career",
    image: 'kak-probitsya-v-kreativ',
    link: "/pages/guides/guides_pages/kak-probitsya-v-kreativ.html",
  },
  {
    id: 41,
    title: "Как выбрать банк для\u00A0первой дебетовой карты",
    category: "finance",
    image: 'pervaya-debetovaya-karta',
    link: "/pages/guides/guides_pages/pervaya-debetovaya-karta.html",
  },
  {
    id: 42,
    title: "Как безопасно оплачивать коммуналку онлайн (чтобы не\u00A0кинули)",
    category: "home",
    image: 'oplachivaem-kommunalku-onlajn',
    link: "/pages/guides/guides_pages/oplachivaem-kommunalku-onlajn.html",
  },
  {
    id: 43,
    title: "Как написать резюме, чтобы тебя заметили среди 500 других",
    category: "career",
    image: 'kak-napisat-rezyume-chtoby-tebya-zametili',
    link: "/pages/guides/guides_pages/kak-napisat-rezyume-chtoby-tebya-zametili.html",
  },
  {
    id: 44,
    title: "Как пережить зиму в\u00A0квартире: советы по\u00A0теплу и\u00A0счетам",
    category: "home",
    image: 'zima-v-kvartire',
    link: "/pages/guides/guides_pages/zima-v-kvartire.html",
  },
  {
    id: 45,
    title: "Что спросить на\u00A0собеседовании, чтобы не\u00A0попасть в\u00A0болото",
    category: "career",
    image: 'chto-sprosit-na-sobesedovanii',
    link: "/pages/guides/guides_pages/chto-sprosit-na-sobesedovanii.html",
  },
  {
    id: 47,
    title: "Как подготовиться к\u00A0приему врача, чтобы не\u00A0забыть спросить важное",
    category: "health",
    image: 'kak-podgotovitsya-k-priemu-vracha-chtoby-ne-zabyt-sprosit-vazhnoe',
    link: "/pages/guides/guides_pages/kak-podgotovitsya-k-priemu-vracha-chtoby-ne-zabyt-sprosit-vazhnoe.html",
  },
  {
    id: 48,
    title: "Как поменять паспорт в\u00A020 и\u00A045",
    category: "docs",
    image: 'zamena-pasporta',
    link: "/pages/guides/guides_pages/zamena-pasporta.html",
  },
  {
    id: 49,
    title: "Как получить загранпаспорт в\u00A02026",
    category: "docs",
    image: 'poluchenie-zagranpasporta',
    link: "/pages/guides/guides_pages/poluchenie-zagranpasporta.html",
  },
  {
    id: 50,
    title: "Как выжить в\u00A0поликлинике: лайфхаки по\u00A0записи, талонам и\u00A0очередям",
    category: "health",
    image: 'kak-vyzhit-v-poliklinike',
    link: "/pages/guides/guides_pages/kak-vyzhit-v-poliklinike.html",

  },
  {
    id: 51,
    title: "Как оформить временную регистрацию при\u00A0переезде",
    category: "docs",
    image: 'oformlenie-vremennoj-registracii',
    link: "/pages/guides/guides_pages/oformlenie-vremennoj-registracii.html",
  },
  {
    id: 52,
    title: "Как пройти собеседование, если\u00A0трясутся коленки",
    category: "career",
    image: 'kak-projti-sobesedovanie-esli-tryasutsya-kolenki',
    link: "/pages/guides/guides_pages/kak-projti-sobesedovanie-esli-tryasutsya-kolenki.html",
  },
  {
    id: 53,
    title: "Рецепты выживания для\u00A0тех, кто\u00A0ненавидит готовить",
    category: "home",
    image: 'recepty-vyzhivaniya',
    link: "/pages/guides/guides_pages/recepty-vyzhivaniya.html",
  },
  {
    id: 56,
    title: "Как посчитать свой реальный доход в\u00A0час",
    category: "finance",
    image: 'kak-poschitat-svoj-realnyj-dohod-v-chas',
    link: "/pages/guides/guides_pages/kak-poschitat-svoj-realnyj-dohod-v-chas.html",
  },
  {
    id: 54,
    title: "Как проверить договор на\u00A0типичные ловушки (без\u00A0юриста)",
    category: "docs",
    image: 'proverka-dogovora',
    link: "/pages/guides/guides_pages/proverka-dogovora.html",
  },
  {
    id: 37,
    title: "Как отвечать на\u00A0вопрос «расскажите о\u00A0себе»",
    category: "career",
    image: 'kak-otvechat-na-vopros-rasskazhite-o-sebe',
    link: "/pages/guides/guides_pages/kak-otvechat-na-vopros-rasskazhite-o-sebe.html",
  },
  {
    id: 55,
    title: "Бюджет на\u00A0переезд, путешествие или\u00A0крупную покупку",
    category: "finance",
    image: 'byudzhet-na-pereezd-puteshestvie-ili-krupnuyu-pokupku',
    link: "/pages/guides/guides_pages/byudzhet-na-pereezd-puteshestvie-ili-krupnuyu-pokupku.html",
  },
];