const HtmlWebpackPlugin = require("html-webpack-plugin");

function createPage(template, filename, chunks){
  return new HtmlWebpackPlugin({
    template: template,
    filename: filename,
    chunks: chunks
  })
}

const htmlPages = [
  createPage('./src/index.html', './index.html',
    ['main', 'index', 'skilltest', 'chart', 'dropdown', 'searchReact', 'searchMobile']),

  createPage('./src/pages/articles/articles.html',
    './pages/articles/articles.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'articlesReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/kvartira-v-novom-gorode.html',
    './pages/articles/articles_pages/kvartira-v-novom-gorode.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/pervyj-mesyac-v-novom-gorode.html',
    './pages/articles/articles_pages/pervyj-mesyac-v-novom-gorode.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
createPage('./src/pages/articles/articles_pages/propiska-voenkomat-polis.html',
    './pages/articles/articles_pages/propiska-voenkomat-polis.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/pochemu-rabotodateli-ne-lyubyat-novichkov.html',
    './pages/articles/articles_pages/pochemu-rabotodateli-ne-lyubyat-novichkov.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/kak-ustroena-adaptaciya-na-pervoj-rabote.html',
    './pages/articles/articles_pages/kak-ustroena-adaptaciya-na-pervoj-rabote.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/ispytatelnyj-srok-ne-daj-sebya-obmanut.html',
    './pages/articles/articles_pages/ispytatelnyj-srok-ne-daj-sebya-obmanut.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/pervaya-mashina-kak-ne-popast-na-dengi.html',
    './pages/articles/articles_pages/pervaya-mashina-kak-ne-popast-na-dengi.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/pochemu-novichki-za-rulem-chashche-popadayut-v-dtp.html',
    './pages/articles/articles_pages/pochemu-novichki-za-rulem-chashche-popadayut-v-dtp.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/strahovka-nalog-to-obyazatelnye-platezhi-avtovladelca.html',
    './pages/articles/articles_pages/strahovka-nalog-to-obyazatelnye-platezhi-avtovladelca.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/pochemu-byt-zhret-vremya-i-kak-ustroena-mentalnaya-nagruzka.html',
    './pages/articles/articles_pages/pochemu-byt-zhret-vremya-i-kak-ustroena-mentalnaya-nagruzka.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/kommunalka-kak-nakruchivayut-pochemu-my-platim-za-soseda-i-chto-takoe-odn.html',
    './pages/articles/articles_pages/kommunalka-kak-nakruchivayut-pochemu-my-platim-za-soseda-i-chto-takoe-odn.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/minimalnyj-nabor-dlya-zhizni.html',
    './pages/articles/articles_pages/minimalnyj-nabor-dlya-zhizni.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/pochemu-prokrastinaciya-pobezhdaet-v-sessiyu.html',
    './pages/articles/articles_pages/pochemu-prokrastinaciya-pobezhdaet-v-sessiyu.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/kak-podgotovitsya-k-zashchite-diploma-i-ne-posedet-za-mesyac-do.html',
    './pages/articles/articles_pages/kak-podgotovitsya-k-zashchite-diploma-i-ne-posedet-za-mesyac-do.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/rabota-i-uchyoba-odnovremenno.html',
    './pages/articles/articles_pages/rabota-i-uchyoba-odnovremenno.html', ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/kak-splanirovat-pervuyu-poezdku-za-granicu.html',
    './pages/articles/articles_pages/kak-splanirovat-pervuyu-poezdku-za-granicu.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/kak-ne-poteryat-dengi-na-kartah-i-obmennikah-v-drugoj-strane.html',
    './pages/articles/articles_pages/kak-ne-poteryat-dengi-na-kartah-i-obmennikah-v-drugoj-strane.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/prosrochennaya-viza-i-poteryannyj-zagranpasport.html',
    './pages/articles/articles_pages/prosrochennaya-viza-i-poteryannyj-zagranpasport.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/kak-ustroen-chernyj-rynok-dokumentov.html',
    './pages/articles/articles_pages/kak-ustroen-chernyj-rynok-dokumentov.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/chto-proiskhodit-s-vashimi-dannymi-esli-telefon-ukrali.html',
    './pages/articles/articles_pages/chto-proiskhodit-s-vashimi-dannymi-esli-telefon-ukrali.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/kvest-po-vosstanovleniyu-pasporta.html',
    './pages/articles/articles_pages/kvest-po-vosstanovleniyu-pasporta.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/pochemu-nas-uvolnyayut-yuridicheskie-i-psihologicheskie-prichiny.html',
    './pages/articles/articles_pages/pochemu-nas-uvolnyayut-yuridicheskie-i-psihologicheskie-prichiny.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/chto-takoe-vyhodnoe-posobie-i-kto-ego-poluchaet.html',
    './pages/articles/articles_pages/chto-takoe-vyhodnoe-posobie-i-kto-ego-poluchaet.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/sokrashchenie-likvidaciya-po-sobstvennomu.html',
    './pages/articles/articles_pages/sokrashchenie-likvidaciya-po-sobstvennomu.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/kto-dolzhen-platit-za-remont-esli-slomalas-tekhnika.html',
    './pages/articles/articles_pages/kto-dolzhen-platit-za-remont-esli-slomalas-tekhnika.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/pochemu-sobstvenniki-ne-vozvrashchayut-depozit-5-samyh-chastyh-skhem.html',
    './pages/articles/articles_pages/pochemu-sobstvenniki-ne-vozvrashchayut-depozit-5-samyh-chastyh-skhem.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/chto-takoe-dogovor-najma.html',
    './pages/articles/articles_pages/chto-takoe-dogovor-najma.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/nestabilnost-na-frilanse.html',
    './pages/articles/articles_pages/nestabilnost-na-frilanse.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/nalogi-dlya-samozanyatyh.html',
    './pages/articles/articles_pages/nalogi-dlya-samozanyatyh.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/frilans-vs-ofis.html',
    './pages/articles/articles_pages/frilans-vs-ofis.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/kak-ustroeno-starenie.html',
    './pages/articles/articles_pages/kak-ustroeno-starenie.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/posobiya-po-uhodu.html',
    './pages/articles/articles_pages/posobiya-po-uhodu.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/besplatnaya-pomoshch-pensioneram.html',
    './pages/articles/articles_pages/besplatnaya-pomoshch-pensioneram.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/ipoteka.html',
    './pages/articles/articles_pages/ipoteka.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/skrytye-raskhody-pri-pokupke-kvartiry.html',
    './pages/articles/articles_pages/skrytye-raskhody-pri-pokupke-kvartiry.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/novostrojka-vs-vtorichka.html',
    './pages/articles/articles_pages/novostrojka-vs-vtorichka.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/razdelnyj-ili-obshchij-byudzhet.html',
    './pages/articles/articles_pages/razdelnyj-ili-obshchij-byudzhet.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/prichina-razvodov.html',
    './pages/articles/articles_pages/prichina-razvodov.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/oplata-dolgov-posle-rasstavaniya.html',
    './pages/articles/articles_pages/oplata-dolgov-posle-rasstavaniya.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/samozanyatost-ip-fizlico.html',
    './pages/articles/articles_pages/samozanyatost-ip-fizlico.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/oshibki-nalogovoj.html',
    './pages/articles/articles_pages/oshibki-nalogovoj.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/kak-rabotaet-ndfl.html',
    './pages/articles/articles_pages/kak-rabotaet-ndfl.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/kak-ustroena-sistema-oms.html',
    './pages/articles/articles_pages/kak-ustroena-sistema-oms.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/informirovannoe-soglasie.html',
    './pages/articles/articles_pages/informirovannoe-soglasie.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/platnaya-vs-besplatnaya-medicina.html',
    './pages/articles/articles_pages/platnaya-vs-besplatnaya-medicina.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/rassrochka-vs-kredit.html',
    './pages/articles/articles_pages/rassrochka-vs-kredit.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/kreditnaya-istoriya.html',
    './pages/articles/articles_pages/kreditnaya-istoriya.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/articles/articles_pages/komu-banki-odobryayut-kredity.html',
    './pages/articles/articles_pages/komu-banki-odobryayut-kredity.html',
    ['main', 'articles', 'dropdown', 'searchReact', 'searchMobile']),

  createPage('./src/pages/guides/guides.html',
    './pages/guides/guides.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'guidesReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/batteries.html',
    './pages/guides/guides_pages/batteries.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/driver-license.html',
    './pages/guides/guides_pages/driver-license.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-projti-stazhirovku-i-poluchit-offer.html',
    './pages/guides/guides_pages/kak-projti-stazhirovku-i-poluchit-offer.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-probitsya-v-kreativ.html',
    './pages/guides/guides_pages/kak-probitsya-v-kreativ.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-prevratit-frilans-v-postoyannyj-dohod.html',
    './pages/guides/guides_pages/kak-prevratit-frilans-v-postoyannyj-dohod.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-prosit-obratnuyu-svyaz.html',
    './pages/guides/guides_pages/kak-prosit-obratnuyu-svyaz.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-vesti-sebya-v-pervyj-mesyac-na-novoj-rabote.html',
    './pages/guides/guides_pages/kak-vesti-sebya-v-pervyj-mesyac-na-novoj-rabote.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-projti-assessment-i-ne-vyletet-na-pervom-zhe-teste.html',
    './pages/guides/guides_pages/kak-projti-assessment-i-ne-vyletet-na-pervom-zhe-teste.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-vesti-peregovory-s-klientom-ili-partnerom.html',
    './pages/guides/guides_pages/kak-vesti-peregovory-s-klientom-ili-partnerom.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-iskat-rabotu-kogda-u-tebya-net-opyta.html',
    './pages/guides/guides_pages/kak-iskat-rabotu-kogda-u-tebya-net-opyta.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-dogovoritsya-o-zarplate.html',
    './pages/guides/guides_pages/kak-dogovoritsya-o-zarplate.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
    createPage('./src/pages/guides/guides_pages/kak-vybrat-kvartiru-i-ne-pozhalet-cherez-mesyac.html',
    './pages/guides/guides_pages/kak-vybrat-kvartiru-i-ne-pozhalet-cherez-mesyac.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-poschitat-svoj-realnyj-dohod-v-chas.html',
    './pages/guides/guides_pages/kak-poschitat-svoj-realnyj-dohod-v-chas.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-otvechat-na-vopros-rasskazhite-o-sebe.html',
    './pages/guides/guides_pages/kak-otvechat-na-vopros-rasskazhite-o-sebe.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/byudzhet-na-pereezd-puteshestvie-ili-krupnuyu-pokupku.html',
    './pages/guides/guides_pages/byudzhet-na-pereezd-puteshestvie-ili-krupnuyu-pokupku.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-projti-sobesedovanie-esli-tryasutsya-kolenki.html',
    './pages/guides/guides_pages/kak-projti-sobesedovanie-esli-tryasutsya-kolenki.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-napisat-rezyume-chtoby-tebya-zametili.html',
    './pages/guides/guides_pages/kak-napisat-rezyume-chtoby-tebya-zametili.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/uvolnenie-po-sobstvennomu-zhelaniyu.html',
    './pages/guides/guides_pages/uvolnenie-po-sobstvennomu-zhelaniyu.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/chto-sprosit-na-sobesedovanii.html',
    './pages/guides/guides_pages/chto-sprosit-na-sobesedovanii.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/pervaya-pomoshch-pri-rasprostranennyh-situaciyah.html',
    './pages/guides/guides_pages/pervaya-pomoshch-pri-rasprostranennyh-situaciyah.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-projti-dispanserizaciyu-ot-zapisi-do-rezultatov.html',
    './pages/guides/guides_pages/kak-projti-dispanserizaciyu-ot-zapisi-do-rezultatov.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-ponyat-chto-u-tebya-depressiya.html',
    './pages/guides/guides_pages/kak-ponyat-chto-u-tebya-depressiya.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-perezhit-bolnichnyj-bez-poteri-deneg-i-nervov.html',
    './pages/guides/guides_pages/kak-perezhit-bolnichnyj-bez-poteri-deneg-i-nervov.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-podgotovitsya-k-priemu-vracha-chtoby-ne-zabyt-sprosit-vazhnoe.html',
    './pages/guides/guides_pages/kak-podgotovitsya-k-priemu-vracha-chtoby-ne-zabyt-sprosit-vazhnoe.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-vyzhit-v-poliklinike.html',
    './pages/guides/guides_pages/kak-vyzhit-v-poliklinike.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-razobratsya-v-receptah-i-ne-kupit-lishnego-v-apteke.html',
    './pages/guides/guides_pages/kak-razobratsya-v-receptah-i-ne-kupit-lishnego-v-apteke.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-ne-sdohnut-ot-allergii-v-sezon.html',
    './pages/guides/guides_pages/kak-ne-sdohnut-ot-allergii-v-sezon.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/tajm-menedzhment-dlya-tekh-kto-nenavidit-planirovat.html',
    './pages/guides/guides_pages/tajm-menedzhment-dlya-tekh-kto-nenavidit-planirovat.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-najti-hobbi.html',
    './pages/guides/guides_pages/kak-najti-hobbi.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/rezhim-kogda-rabotaesh-iz-doma.html',
    './pages/guides/guides_pages/rezhim-kogda-rabotaesh-iz-doma.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-polzovatsya-lyubym-planerom-bez-fanatizma.html',
    './pages/guides/guides_pages/kak-polzovatsya-lyubym-planerom-bez-fanatizma.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-perezhit-rasstavanie.html',
    './pages/guides/guides_pages/kak-perezhit-rasstavanie.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/druzya-vo-vzroslom-vozraste.html',
    './pages/guides/guides_pages/druzya-vo-vzroslom-vozraste.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/perestat-zavisat-v-telefone-pered-snom.html',
    './pages/guides/guides_pages/perestat-zavisat-v-telefone-pered-snom.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/recepty-vyzhivaniya.html',
    './pages/guides/guides_pages/recepty-vyzhivaniya.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/perestat-stesnyatsya-sebya.html',
    './pages/guides/guides_pages/perestat-stesnyatsya-sebya.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kak-vesti-byudzhet.html',
    './pages/guides/guides_pages/kak-vesti-byudzhet.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/kreditka-bez-procentov.html',
    './pages/guides/guides_pages/kreditka-bez-procentov.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/moshenniki-v-internete.html',
    './pages/guides/guides_pages/moshenniki-v-internete.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/chitaem-vypisku-po-karte.html',
    './pages/guides/guides_pages/chitaem-vypisku-po-karte.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
    createPage('./src/pages/guides/guides_pages/kak-nachat-otkladyvat.html',
    './pages/guides/guides_pages/kak-nachat-otkladyvat.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/pervaya-debetovaya-karta.html',
    './pages/guides/guides_pages/pervaya-debetovaya-karta.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/oplachivaem-kommunalku-onlajn.html',
    './pages/guides/guides_pages/oplachivaem-kommunalku-onlajn.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/bytovaya-himiya.html',
    './pages/guides/guides_pages/bytovaya-himiya.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/zima-v-kvartire.html',
    './pages/guides/guides_pages/zima-v-kvartire.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/zavesti-pitomca.html',
    './pages/guides/guides_pages/zavesti-pitomca.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/sdacha-kvartiry-v-arendu.html',
    './pages/guides/guides_pages/sdacha-kvartiry-v-arendu.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/poluchenie-zagranpasporta.html',
    './pages/guides/guides_pages/poluchenie-zagranpasporta.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/zamena-pasporta.html',
    './pages/guides/guides_pages/zamena-pasporta.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/oformlenie-inn.html',
    './pages/guides/guides_pages/oformlenie-inn.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/poluchenie-spravki-2-ndfl.html',
    './pages/guides/guides_pages/poluchenie-spravki-2-ndfl.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/oformlenie-vremennoj-registracii.html',
    './pages/guides/guides_pages/oformlenie-vremennoj-registracii.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/vosstanovlenie-snils.html',
    './pages/guides/guides_pages/vosstanovlenie-snils.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/dokumenty-na-nalogovyj-vychet.html',
    './pages/guides/guides_pages/dokumenty-na-nalogovyj-vychet.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),
  createPage('./src/pages/guides/guides_pages/proverka-dogovora.html',
    './pages/guides/guides_pages/proverka-dogovora.html',
    ['main', 'guides', 'dropdown', 'searchReact', 'searchMobile']),

  createPage('./src/pages/dictionary/dictionary.html',
    './pages/dictionary/dictionary.html',
    ['main', 'dictionary', 'dropdown', 'searchReact', 'glossaryReact', 'searchMobile']),

  createPage('./src/pages/styleguide/styleguide.html',
    './pages/styleguide/styleguide.html',
    ['styleguide']),

  createPage('./src/pages/errors/404.html', './404.html', ['main', 'errors']),
  createPage('./src/pages/errors/500.html', './500.html', ['main', 'errors']),
  createPage('./src/pages/errors/505.html', './505.html', ['main', 'errors'])
];

module.exports = htmlPages;